# Generated by Django 5.0 on 2025-12-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lib', '0009_apuntecalificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apunte',
            name='asignatura',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='apunte',
            name='carrera',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='apunte',
            name='titulo',
            field=models.CharField(max_length=40),
        ),
    ]
