# Generated by Django 5.0 on 2025-12-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lib', '0010_alter_apunte_asignatura_alter_apunte_carrera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apunte',
            name='asignatura',
            field=models.TextField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='apunte',
            name='carrera',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
